import "VisualizationSource.idl";

namespace AudioVisualizer
{
	[default_interface]
	runtimeclass AnalogVUMeter : Windows.UI.Xaml.Controls.Control
	{
		AnalogVUMeter();
		IVisualizationSource Source;
		Int32 ChannelIndex;
	}
}
