namespace AudioVisualizer
{
	runtimeclass AudioViewDataBuffer;

	[default_interface]
	runtimeclass AudioViewDataBufferCreateProgress
	{
		Object Buffer;
		Windows.Foundation.TimeSpan DataLoaded;
		UInt32 Progress;
	};
}
