
namespace AudioVisualizer
{
	[default_interface]
	runtimeclass AudioViewData
	{
		AudioViewData(UInt32 reserveCapacity,UInt32 detailLevels,UInt32 downsample);
		void Add(Windows.Foundation.Collections.IIterable<Single> data);
	};
}
