namespace AudioVisualizer
{
	[default_interface]
	runtimeclass AudioViewData
	{
		AudioViewData();
		void Append(Windows.Media.AudioFrame frame);
		[method_name("AppendWithStrideAndOffset")] 
		void Append(Windows.Media.AudioFrame frame, UInt32 stride, UInt32 offset);
	}
}
