import "EnumTypes.idl";
import "VisualizationDataFrame.idl";

namespace AudioVisualizer
{
	[default_interface]
	runtimeclass AudioAnalyzer : Windows.Foundation.IClosable
	{
		AudioAnalyzer(UInt32 bufferSize, UInt32 inputChannels, UInt32 sampleRate, UInt32 inputStep, UInt32 inputOverlap, UInt32 fftLength,Boolean backgroundProcessing);
		void ProcessInput(Windows.Media.AudioFrame frame);

		AnalyzerType AnalyzerTypes;
		Single SpectrumStep { get; };
		UInt32 SpectrumElementCount{ get; };
		Boolean IsSuspended;
		void Flush();
		void Flush(Int64 seedPosition);

		event Windows.Foundation.TypedEventHandler<AudioAnalyzer, VisualizationDataFrame> Output;
	}
}
