
namespace AudioVisualizer
{
	struct MeterBarLevel
	{
		Single Level;
		Windows.UI.Color Color;
	};

	interface IBarVisualizer : IInspectable
	{
		MeterBarLevel[] Levels;
		Windows.UI.Xaml.Controls.Orientation Orientation;
		Int32 ChannelIndex;
		Windows.UI.Xaml.Thickness RelativeElementMargin;
		Windows.UI.Color UnlitElement;
	}
}
