namespace AudioVisualizer
{
	struct ContentScaleRange {
		Double From;
		Double To;
	};
	
	interface IContentScaleManager : IInspectable {
		ContentScaleRange GetRange(Double value);
	};

	[default_interface]
	runtimeclass BinaryScaleManager : IContentScaleManager
	{
		BinaryScaleManager();
		BinaryScaleManager(UInt32 offset, UInt32 step); 
	};
}