import "VisualizerControl.idl";
import "BarVisualizer.idl";

namespace AudioVisualizer
{
	[default_interface]
	runtimeclass DiscreteVUBar : VisualizerControl, IBarVisualizer
	{
		DiscreteVUBar();
		Boolean DisplayPeak;
	}
}

