import "VisualizerControl.idl";
import "BarVisualizer.idl";

namespace AudioVisualizer
{
	[default_interface]
	runtimeclass DiscreteVUBar : Windows.UI.Xaml.Controls.Control, IBarVisualizer
	{
		DiscreteVUBar();
		Boolean DisplayPeak;
		IVisualizationSource Source;
	}
}

