import "VisualizationSource.idl";
import "SpectralAnalyzer.idl";

namespace AudioVisualizer
{
	[default_interface]
	runtimeclass LoopbackVisualizationSource : IVisualizationSource, ISpectralAnalyzer
	{
		static Windows.Foundation.IAsyncOperation<LoopbackVisualizationSource> CreateAsync();
		static Windows.Foundation.IAsyncOperation<LoopbackVisualizationSource> CreateAsync(Windows.Devices.Enumeration.DeviceInformation renderDevice);
	}
}
