import "VisualizationSource.idl";

namespace AudioVisualizer
{
	[default_interface]
	runtimeclass PlaybackSource {

		PlaybackSource (Windows.Media.Playback.MediaPlayer mediaPlayer);
		IVisualizationSource Source{ get; };
		
		event Windows.Foundation.TypedEventHandler<Object,IVisualizationSource> SourceChanged;
	}
}