namespace AudioVisualizer
{
	struct ScaleRange {
		Double From;
		Double To;
	};
	
	interface IScaleManager : IInspectable {
		ScaleRange GetRange(Double value);
	};

	[default_interface]
	runtimeclass BinaryScaleManager : IScaleManager
	{
		BinaryScaleManager();
		BinaryScaleManager(UInt32 offset, UInt32 step); 
	};
}