import "Types.idl";

namespace AudioVisualizer
{
	[default_interface]
	runtimeclass ScalarData
	{
		static ScalarData CreateEmpty(UInt32 channels);
		static ScalarData Create(Single[] values);
		ScaleType AmplitudeScale{ get; };
		ScalarData ConvertToDecibels(Single minValue, Single maxValue);
		ScalarData ApplyRiseAndFall(ScalarData previous, Windows.Foundation.TimeSpan riseTime, Windows.Foundation.TimeSpan fallTime, Windows.Foundation.TimeSpan timeFromPrevious);
		static ScalarData ApplyRiseAndFallToEmpty(ScalarData previous, Windows.Foundation.TimeSpan riseTime, Windows.Foundation.TimeSpan fallTime, Windows.Foundation.TimeSpan timeFromPrevious);
	}
}
