import "VisualizerControl.idl";
import "BarVisualizer.idl";
import "EnumTypes.idl";

namespace AudioVisualizer
{
	[default_interface]
	runtimeclass SpectrumVisualizer : VisualizerControl, IBarVisualizer
	{
		SpectrumVisualizer();
		SpectrumVisualizationStyle SpectrumStyle;
	}
}