import "VisualizerControl.idl";
import "BarVisualizer.idl";

namespace AudioVisualizer
{
	[default_interface]
	runtimeclass SpectrumVisualizer : VisualizerControl, IBarVisualizer
	{
		SpectrumVisualizer();
	}
}