import "contentscalemanager.idl";

namespace AudioVisualizer
{
	struct TileIndexRange {
		Int32 From;
		Int32 To;
	};

	enum TileSizeLimitType {
		MinimumSize = 0,
		MaximumSize = 1
	};

	[default_interface]
	runtimeclass TiledViewManager  {
		Single ViewportSize;
		Single ViewportOffset;
		Double Zoom;
		Double Resolution;
		Double ContentOffset;
		Double ContentSize;
		Single TileSizeLimit;
		TileIndexRange TileRange{ get; };
		ContentScaleRange ScaleRange{ get; };
		Double Scale{ get; };
		TiledViewManager();
		Single ContentToView(Double value);
		Double ViewToContent(Single value);

		event Windows.Foundation.EventHandler<IInspectable> RangeChanged;
		event Windows.Foundation.EventHandler<IInspectable> ScaleChanged;
	}

}
