import "Windows.Foundation.idl";

namespace AudioVisualizer
{
	[uuid(E4C11BE5-112E-49AD-A565-EE713089C447)]
	[version(1.0)]
	interface IVisualizationData : IInspectable {
		[propget] HRESULT AudioChannels([out, retval] unsigned *result);
	};

	[version(1.0)]
	runtimeclass VisualizationData
	{
		[default] interface IVisualizationData;
	}

}
