import "VisualizationSource.idl";

namespace AudioVisualizer
{
	[default_interface]
	unsealed runtimeclass VisualizerControl : Windows.UI.Xaml.Controls.Control
	{
		VisualizerControl();
		IVisualizationSource Source;
		Windows.UI.Color BackgroundColor;
	};
}

